# =========================================================================
# COTTONPAY - CONFIGURATION INJI CERTIFY (UTILISANT LE PLUGIN POSTGRES NATIF)
# =========================================================================

# 1. On dit à Inji d'utiliser son propre plugin Postgres (pas besoin de compiler de Java !)
mosip.certify.integration.data-provider-plugin=PostgresDataProviderPlugin

# 2. Configuration de la base de données PostgreSQL
mosip.certify.data-provider-plugin.postgres.db.url=jdbc:postgresql://database:5432/mosip_esignet
mosip.certify.data-provider-plugin.postgres.db.username=postgres
mosip.certify.data-provider-plugin.postgres.db.password=postgres
mosip.certify.data-provider-plugin.postgres.db.schema=certify

# 3. La MAGIE de MOSIP : On mappe la permission OIDC avec notre propre requête SQL !
mosip.certify.data-provider-plugin.postgres.scope-query-mapping={\
    'openid': 'select \
        transaction_id as "transactionId", \
        farmer_name as "farmerName", \
        farmer_npi as "farmerNPI", \
        farmer_phone as "farmerPhone", \
        cotton_weight_kg as "cottonWeightKg", \
        unit_price_fcfa as "unitPriceFCFA", \
        total_amount_fcfa as "totalAmountFCFA", \
        TO_CHAR(sale_date, ''YYYY-MM-DD'') as "saleDate", \
        TO_CHAR(sale_time, ''HH24:MI:SS'') as "saleTime", \
        payment_reference as "paymentReference", \
        payment_status as "paymentStatus", \
        payment_method as "paymentMethod", \
        ''CottonPay ID - Bénin'' as "issuedBy" \
    from cottonpay_sales \
    where farmer_npi=:id \
    order by cr_dtimes desc \
    limit 1'\
}

# --- SURCHARGES DE SECURITE LOCALES ---
mosip.certify.authorization.url=http://host.docker.internal:8088
mosip.certify.authn.issuer-uri=http://localhost:8088/v1/esignet
mosip.certify.authn.jwk-set-uri=http://host.docker.internal:8088/v1/esignet/oauth/.well-known/jwks.json
mosip.certify.authn.allowed-audiences={ 'cottonpay-client', 'http://localhost:8091/v1/certify/issuance/credential', 'cottonpay-rp' }
mosip.certify.security.ignore-auth-urls=**/actuator/**,**/error,**/swagger-ui/**,**/v3/api-docs/**,**/issuance/credential,**/issuance/**
